import type { UiLanguage } from "./ui-language";

type CopyFor<T> = {
  [K in keyof T]: T[K] extends (...args: infer Args) => string
    ? (...args: Args) => string
    : T[K] extends string
      ? string
      : CopyFor<T[K]>;
};

const en = {
  common: {
    signIn: "Sign in",
    language: "Language",
    itemCount: (count: number) =>
      `${new Intl.NumberFormat("en").format(count)} ${count === 1 ? "item" : "items"}`,
  },
  errors: {
    unexpected: "Something went wrong. Please try again.",
    signUp: "We couldn't create your account.",
    signIn: "We couldn't sign you in.",
    resetLink: "We couldn't send the reset link.",
    invalidToken: "Invalid or expired token",
    invalidCredentials: "Invalid email or password",
    invalidInput: "Please check your information and try again.",
    rateLimited: "Too many attempts. Please try again later.",
    profileSave: "We couldn't save your profile. Please try again.",
    passwordLength: "Password must contain 12–128 Unicode characters.",
  },
  auth: {
    email: "Email address",
    password: "Password",
    displayName: "Display name",
    checkEmail: "Check your email",
    signUpTitle: "Create your account",
    signUpDescription: "Start a private planning space for your celebration.",
    signUpSent: "We sent a verification link if the address can receive one.",
    signUpNext:
      "Open the link in your email to verify your address before signing in.",
    signUpAlternate: "Already registered? Sign in",
    passwordHelp: "Use 12–128 characters. Spaces and Unicode are welcome.",
    creating: "Creating account…",
    createAccount: "Create account",
    signInTitle: "Welcome back",
    signInDescription: "Sign in to continue planning your chapter.",
    signInAlternate: "New here? Create an account",
    forgotPassword: "Forgot password?",
    signingIn: "Signing in…",
    signIn: "Sign in",
    verifyTitle: "Verify your email",
    verifiedTitle: "Email verified",
    verifyDescription: "We're checking your secure verification link.",
    verifiedDescription: "Your address is verified. You can sign in now.",
    verifying: "Verifying your email…",
    verified: "Verification complete.",
    continueSignIn: "Continue to sign in",
    forgotTitle: "Reset your password",
    forgotDescription: "Enter your email and we'll send a secure reset link.",
    forgotSent: "If an eligible account exists, a reset link is on its way.",
    forgotNext:
      "If an eligible account exists, you will receive an email shortly.",
    returnSignIn: "Return to sign in",
    sending: "Sending…",
    sendReset: "Send reset link",
    resetTitle: "Choose a new password",
    resetCompleteTitle: "Password reset",
    resetDescription: "Use 12–128 characters. Your password is never trimmed.",
    resetCompleteDescription:
      "Your sessions were closed and your new password is ready.",
    newPassword: "New password",
    resetting: "Resetting…",
    resetPassword: "Reset password",
    resetReading: "Reading your secure reset link…",
    signInNewPassword: "Sign in with your new password",
  },
  profile: {
    eyebrow: "One last detail",
    title: "How should we welcome you?",
    description:
      "This name appears in your private wedding workspace. You can use any language.",
    displayName: "Display name",
    nameLength: "Display name must be 1–120 characters",
    saving: "Saving…",
    continue: "Continue to LoveChapter",
  },
  session: {
    checking: "Checking your session…",
    errorTitle: "We couldn't restore your session.",
    errorDescription:
      "The service may be temporarily unavailable. Your account state has not been changed.",
    boundaryTitle: "We couldn't open your private workspace.",
    boundaryDescription:
      "Your invitation pages are unaffected. Try loading your account again.",
    retry: "Try again",
  },
  pageTitles: {
    signUp: "Create account",
    signIn: "Sign in",
    verifyEmail: "Verify email",
    forgotPassword: "Forgot password",
    resetPassword: "Reset password",
    invitation: "Private invitation",
  },
  rsvp: {
    opening: "Opening your invitation…",
    loadTitle: "We couldn't open this invitation",
    loadError: "We couldn't load this invitation. Please try again.",
    unavailableTitle: "Invitation unavailable",
    unavailableDescription:
      "This invitation may have expired or been replaced. Please ask the couple for a new link.",
    retry: "Try again",
    celebration: "A celebration of love",
    invited: "You're invited,",
    welcome: "Join us as we begin a beautiful new chapter together.",
    timeZone: (zone: string) => `Times shown in ${zone}`,
    datePending: "Date to be announced",
    badge: "Private RSVP",
    heading: "Will you join us?",
    editable: "Your response can be updated later using this same invitation.",
    response: "Your response",
    attending: "Joyfully accept",
    declined: "Regretfully decline",
    partySize: "Party size",
    partySizeOption: (size: number) =>
      `${size} ${size === 1 ? "guest" : "guests"}`,
    partyLimit: (size: number) => `This invitation welcomes up to ${size}.`,
    note: "Note (optional)",
    notePlaceholder: "Share a warm note with the couple…",
    saving: "Saving…",
    submit: "Save RSVP",
    saved: "Your RSVP is saved.",
    saveError: "We couldn't save your RSVP. Please try again.",
    invalidInput: "Please check your response and try again.",
    privateLink:
      "No account or password is needed. Keep this private invitation link safe.",
  },
  workspace: {
    label: "Wedding workspace",
    signOut: "Sign out",
    eyebrow: "Your story, thoughtfully gathered",
    title: "Plan the chapter everyone will remember.",
    description:
      "Start with one wedding, welcome your guests, and keep every reply in one calm place.",
    opening: "Opening your workspace…",
    weddings: "Your weddings",
    open: "Open",
    loading: "Loading…",
    loadMoreWeddings: "Load more weddings",
    beginTitle: "Begin with the day",
    beginDescription:
      "Create your wedding to unlock the guest list and private RSVP invitations. You can keep the date open for now.",
    createTitle: "Create a wedding",
    createDescription: "A home for this celebration.",
    weddingName: "Wedding name",
    weddingDate: "Wedding date (optional)",
    timeZone: "Time zone",
    locale: "Locale",
    creating: "Creating…",
    create: "Create wedding",
    current: "Currently planning",
    datePending: "Date to be announced",
    addGuestTitle: "Add a guest",
    addGuestDescription: "Each guest receives a private invitation link.",
    guestName: "Guest name",
    emailOptional: "Email (optional)",
    guestAffiliation: "Guest affiliation",
    noAffiliation: "No affiliation",
    partyAllowance: "Party allowance",
    adding: "Adding…",
    addGuest: "Add guest",
    responses: "Responses",
    guestList: "Guest list",
    loaded: (count: number) =>
      `${new Intl.NumberFormat("en").format(count)} loaded`,
    refreshing: "Refreshing…",
    refreshResponses: "Refresh responses",
    noGuests: "No guests yet",
    noGuestsDescription: "Add your first guest above when you are ready.",
    upTo: (count: number) =>
      `Up to ${new Intl.NumberFormat("en").format(count)} attending`,
    createInvitation: "Create invitation",
    invitationNotice:
      "This secure link is shown only for this session. Copy it before leaving.",
    copyInvitation: "Copy invitation link",
    copied: "Copied",
    loadMoreGuests: "Load more guests",
    awaiting: "Awaiting response",
    attending: (count: number) =>
      `Attending · ${new Intl.NumberFormat("en").format(count)}`,
    declined: "Declined",
    affiliationEyebrow: "Organize your guests",
    affiliationTitle: "Guest affiliations",
    affiliationDescription:
      "Create the affiliations that fit this wedding. Nothing is predefined, and deleting one keeps its guests as unassigned.",
    newAffiliation: "New affiliation name",
    color: "Color",
    addAffiliation: "Add affiliation",
    noAffiliations:
      "No affiliations yet. Guests can still be added without one.",
    save: "Save",
    moveUp: (name: string) => `Move ${name} up`,
    moveDown: (name: string) => `Move ${name} down`,
    delete: (name: string) => `Delete ${name}`,
    affiliationName: (name: string) => `${name} name`,
    affiliationColor: (name: string) => `${name} color`,
    guestAffiliationLabel: (name: string) => `${name} affiliation`,
    openInvitation: (name: string) => `Open ${name}'s invitation`,
    deleteAffiliationConfirm: (name: string) =>
      `Delete “${name}”? Guests in this affiliation will become unassigned.`,
    disconnected:
      "The planning workspace is not connected yet. Please try again.",
    createError: "We couldn't create that wedding.",
    guestListError: "We couldn't load this guest list.",
    addGuestError: "We couldn't add that guest.",
    addAffiliationError: "We couldn't add that affiliation.",
    updateAffiliationError: "We couldn't update that affiliation.",
    reorderAffiliationError: "We couldn't reorder affiliations.",
    deleteAffiliationError: "We couldn't delete that affiliation.",
    setAffiliationError: "We couldn't change that guest affiliation.",
    invitationError: "We couldn't create that invitation.",
    moreWeddingsError: "We couldn't load more weddings.",
    moreGuestsError: "We couldn't load more guests.",
    refreshError: "We couldn't refresh responses.",
    copyError: "Copy failed. Select the invitation link and copy it manually.",
  },
  planning: {
    eyebrow: "Preparation",
    title: "Planning checklist",
    description: (name: string) =>
      `Keep your tasks and deadlines together for ${name}.`,
    progress: "Planning progress",
    completedCount: (completed: number, total: number) =>
      `${new Intl.NumberFormat("en").format(completed)} of ${new Intl.NumberFormat("en").format(total)} complete`,
    tasksCompleted: "Tasks completed",
    editTask: "Edit task",
    addTaskTitle: "Add a task",
    taskTitle: "Task title",
    category: "Category (optional)",
    dueDate: "Due date (optional)",
    note: "Private note (optional)",
    saveTask: "Save task",
    addTask: "Add task",
    cancelEdit: "Cancel edit",
    comingUp: "Coming up",
    overdue: "Overdue",
    allTasks: "All tasks",
    showTasks: "Show tasks",
    all: "All",
    toDo: "To do",
    completed: "Completed",
    loading: "Loading tasks…",
    empty: "No tasks yet.",
    due: (date: string) => `Due ${date}`,
    noDueDate: "No due date",
    complete: "Complete",
    reopen: "Reopen",
    edit: "Edit",
    delete: "Delete",
    actionLabel: (action: string, title: string) => `${action} ${title}`,
    deleteConfirm: (title: string) =>
      `Delete “${title}”? This cannot be undone.`,
    loadMore: "Load more tasks",
    loadError: "Could not load the planning checklist.",
    saveError: "Could not save this task.",
    updateError: "Could not update this task.",
    deleteError: "Could not delete this task.",
    moreError: "Could not load more tasks.",
  },
  guest: {
    search: "Search guests",
    searchPlaceholder: "Name, email, or phone",
    view: "Guest view",
    active: "Active",
    archived: "Archived",
    affiliation: "Affiliation",
    allAffiliations: "All affiliations",
    unassigned: "Unassigned",
    rsvpStatus: "RSVP status",
    allStatuses: "All RSVP statuses",
    pending: "Pending",
    attending: "Attending",
    declined: "Declined",
    guestList: "Guest list",
    listCount: (loaded: number, selected: number) =>
      `${new Intl.NumberFormat("en").format(loaded)} loaded · ${new Intl.NumberFormat("en").format(selected)} selected`,
    selectVisible: "Select visible guests",
    select: (name: string) => `Select ${name}`,
    bulkAffiliation: "Bulk affiliation",
    assignSelected: "Assign selected",
    archiveSelected: "Archive selected",
    noMatches: "No guests match these filters.",
    upTo: (count: number) =>
      `Up to ${new Intl.NumberFormat("en").format(count)} attending`,
    edit: "Edit",
    archive: "Archive",
    restore: "Restore",
    action: (verb: string, name: string) => `${verb} ${name}`,
    createInvitation: "Create invitation",
    issueNewLink: "Issue new invitation link",
    issueNewLinkFor: (name: string) => `Issue a new link for ${name}`,
    replaceHint:
      "If a link already exists, issuing a new one stops the old link from working.",
    openInvitation: (name: string) => `Open ${name}'s invitation`,
    invitationNotice:
      "This secure link is shown only for this session. Copy it before leaving.",
    copyInvitation: "Copy invitation link",
    loading: "Loading…",
    loadMore: "Load more guests",
    awaiting: "Awaiting response",
    attendingCount: (count: number) =>
      `Attending · ${new Intl.NumberFormat("en").format(count)}`,
    guestName: "Guest name",
    emailOptional: "Email (optional)",
    email: "Email",
    guestAffiliation: "Guest affiliation",
    noAffiliation: "No affiliation",
    partyAllowance: "Party allowance",
    optionalDetails: "Optional contact, envelope, and mailing details",
    phone: "Phone",
    envelopeName: "Envelope name",
    note: "Note",
    includeAddress: "Include postal address",
    adding: "Adding…",
    addGuest: "Add guest",
    addressLine1: "Address line 1",
    addressLine2: "Address line 2",
    locality: "Locality",
    administrativeArea: "Administrative area",
    postalCode: "Postal code",
    countryCode: "Country code",
    editGuest: (name: string) => `Edit ${name}`,
    close: "Close",
    saving: "Saving…",
    saveGuest: "Save guest",
    archiveConfirm: (name: string) => `Archive ${name}?`,
    bulkArchiveConfirm: (count: number) =>
      `Archive ${count} guest${count === 1 ? "" : "s"}? Their invitation links will be revoked.`,
    replaceConfirm: (name: string) =>
      `Issue a new invitation link for ${name}? Any old link will stop working immediately. Share the new link with the guest.`,
    current: "Currently planning",
    addGuestTitle: "Add a guest",
    csvNotice:
      "Archived guests export only in Archived view. Invitation links are never included.",
    exportCsv: "Export filtered CSV",
    closeEnvelopes: "Close envelope printing",
    printEnvelopes: "Print envelopes",
    refresh: "Refresh responses",
    loadError: "We couldn't load guests.",
    addError: "We couldn't add that guest.",
    detailError: "We couldn't load that guest.",
    saveError: "We couldn't save that guest.",
    archiveError: "We couldn't archive that guest.",
    restoreError: "We couldn't restore that guest.",
    bulkAffiliationError: "Bulk affiliation failed.",
    bulkArchiveError: "Bulk archive failed.",
    invitationError: "We couldn't create that invitation.",
    replaceError: "We couldn't replace that invitation.",
    copyError: "Copy failed. Select the invitation link and copy it manually.",
    exportError: "We couldn't export the guest CSV.",
  },
  metadata: {
    title: "LoveChapter — Wedding planning & RSVP",
    description:
      "A calm wedding workspace for couples and a private, account-free RSVP for guests.",
  },
  maintenance: {
    title: "LoveChapter is temporarily unavailable",
    message: "Service temporarily unavailable. Please try again shortly.",
    notice:
      "After the release, returning tabs reload automatically. Unsaved form input in this tab may be lost.",
    applyLanguage: "Change language",
  },
};

export type UiCopy = CopyFor<typeof en>;

const th: UiCopy = {
  common: {
    signIn: "เข้าสู่ระบบ",
    language: "ภาษา",
    itemCount: (count) => `${new Intl.NumberFormat("th").format(count)} รายการ`,
  },
  errors: {
    unexpected: "เกิดข้อผิดพลาด กรุณาลองอีกครั้ง",
    signUp: "ไม่สามารถสร้างบัญชีได้ กรุณาลองอีกครั้ง",
    signIn: "ไม่สามารถเข้าสู่ระบบได้ กรุณาลองอีกครั้ง",
    resetLink: "ไม่สามารถส่งลิงก์ตั้งรหัสผ่านใหม่ได้ กรุณาลองอีกครั้ง",
    invalidToken: "ลิงก์ไม่ถูกต้องหรือหมดอายุแล้ว",
    invalidCredentials: "อีเมลหรือรหัสผ่านไม่ถูกต้อง",
    invalidInput: "กรุณาตรวจสอบข้อมูลแล้วลองอีกครั้ง",
    rateLimited: "ลองหลายครั้งเกินไป กรุณาลองใหม่ภายหลัง",
    profileSave: "ไม่สามารถบันทึกโปรไฟล์ได้ กรุณาลองอีกครั้ง",
    passwordLength: "รหัสผ่านต้องมี 12–128 อักขระยูนิโค้ด",
  },
  auth: {
    email: "อีเมล",
    password: "รหัสผ่าน",
    displayName: "ชื่อที่แสดง",
    checkEmail: "ตรวจสอบอีเมลของคุณ",
    signUpTitle: "สร้างบัญชี",
    signUpDescription: "เริ่มพื้นที่วางแผนงานแต่งส่วนตัวของคุณ",
    signUpSent: "เราส่งลิงก์ยืนยันแล้ว หากอีเมลนี้รับข้อความได้",
    signUpNext: "เปิดลิงก์ในอีเมลเพื่อยืนยันที่อยู่ก่อนเข้าสู่ระบบ",
    signUpAlternate: "มีบัญชีแล้ว? เข้าสู่ระบบ",
    passwordHelp: "ใช้ 12–128 อักขระ เว้นวรรคและยูนิโค้ดได้",
    creating: "กำลังสร้างบัญชี…",
    createAccount: "สร้างบัญชี",
    signInTitle: "ยินดีต้อนรับกลับ",
    signInDescription: "เข้าสู่ระบบเพื่อวางแผนงานแต่งต่อ",
    signInAlternate: "ยังไม่มีบัญชี? สร้างบัญชี",
    forgotPassword: "ลืมรหัสผ่าน?",
    signingIn: "กำลังเข้าสู่ระบบ…",
    signIn: "เข้าสู่ระบบ",
    verifyTitle: "ยืนยันอีเมลของคุณ",
    verifiedTitle: "ยืนยันอีเมลแล้ว",
    verifyDescription: "กำลังตรวจสอบลิงก์ยืนยันที่ปลอดภัย",
    verifiedDescription: "ยืนยันอีเมลแล้ว คุณเข้าสู่ระบบได้เลย",
    verifying: "กำลังยืนยันอีเมล…",
    verified: "ยืนยันอีเมลสำเร็จ",
    continueSignIn: "ไปหน้าเข้าสู่ระบบ",
    forgotTitle: "ตั้งรหัสผ่านใหม่",
    forgotDescription: "กรอกอีเมล แล้วเราจะส่งลิงก์ตั้งรหัสผ่านใหม่ให้",
    forgotSent: "หากมีบัญชีที่เข้าเงื่อนไข เราจะส่งลิงก์ให้ทางอีเมล",
    forgotNext: "หากมีบัญชีที่เข้าเงื่อนไข คุณจะได้รับอีเมลในไม่ช้า",
    returnSignIn: "กลับไปหน้าเข้าสู่ระบบ",
    sending: "กำลังส่ง…",
    sendReset: "ส่งลิงก์ตั้งรหัสผ่านใหม่",
    resetTitle: "เลือกรหัสผ่านใหม่",
    resetCompleteTitle: "ตั้งรหัสผ่านใหม่แล้ว",
    resetDescription: "ใช้ 12–128 อักขระ ระบบจะไม่ตัดช่องว่างออกจากรหัสผ่าน",
    resetCompleteDescription:
      "ออกจากระบบทุกอุปกรณ์แล้ว และใช้รหัสผ่านใหม่ได้ทันที",
    newPassword: "รหัสผ่านใหม่",
    resetting: "กำลังตั้งรหัสผ่านใหม่…",
    resetPassword: "ตั้งรหัสผ่านใหม่",
    resetReading: "กำลังอ่านลิงก์ตั้งรหัสผ่านใหม่…",
    signInNewPassword: "เข้าสู่ระบบด้วยรหัสผ่านใหม่",
  },
  profile: {
    eyebrow: "อีกขั้นตอนเดียว",
    title: "อยากให้เราเรียกคุณว่าอะไร?",
    description: "ชื่อนี้จะแสดงในพื้นที่งานแต่งส่วนตัวของคุณ ใช้ภาษาใดก็ได้",
    displayName: "ชื่อที่แสดง",
    nameLength: "ชื่อที่แสดงต้องมี 1–120 อักขระ",
    saving: "กำลังบันทึก…",
    continue: "เข้าสู่ LoveChapter",
  },
  session: {
    checking: "กำลังตรวจสอบการเข้าสู่ระบบ…",
    errorTitle: "ไม่สามารถคืนค่าการเข้าสู่ระบบได้",
    errorDescription:
      "บริการอาจไม่พร้อมใช้งานชั่วคราว ข้อมูลบัญชีของคุณไม่เปลี่ยนแปลง",
    boundaryTitle: "ไม่สามารถเปิดพื้นที่ส่วนตัวของคุณได้",
    boundaryDescription: "หน้าคำเชิญยังใช้งานได้ กรุณาลองโหลดบัญชีอีกครั้ง",
    retry: "ลองอีกครั้ง",
  },
  pageTitles: {
    signUp: "สร้างบัญชี",
    signIn: "เข้าสู่ระบบ",
    verifyEmail: "ยืนยันอีเมล",
    forgotPassword: "ลืมรหัสผ่าน",
    resetPassword: "ตั้งรหัสผ่านใหม่",
    invitation: "คำเชิญส่วนตัว",
  },
  rsvp: {
    opening: "กำลังเปิดคำเชิญ…",
    loadTitle: "ไม่สามารถเปิดคำเชิญนี้ได้",
    loadError: "ไม่สามารถโหลดคำเชิญได้ กรุณาลองอีกครั้ง",
    unavailableTitle: "คำเชิญนี้ไม่พร้อมใช้งาน",
    unavailableDescription:
      "คำเชิญอาจหมดอายุหรือถูกเปลี่ยนแล้ว กรุณาขอลิงก์ใหม่จากคู่บ่าวสาว",
    retry: "ลองอีกครั้ง",
    celebration: "วันแห่งความรัก",
    invited: "ขอเชิญคุณ",
    welcome: "มาร่วมฉลองการเริ่มต้นบทใหม่ที่สวยงามไปด้วยกัน",
    timeZone: (zone) => `แสดงเวลาในเขตเวลา ${zone}`,
    datePending: "จะแจ้งวันที่ให้ทราบภายหลัง",
    badge: "ตอบรับคำเชิญส่วนตัว",
    heading: "คุณจะมาร่วมงานไหม?",
    editable: "คุณกลับมาแก้ไขคำตอบได้ภายหลังผ่านคำเชิญนี้",
    response: "คำตอบของคุณ",
    attending: "ยินดีไปร่วมงาน",
    declined: "ไม่สามารถไปร่วมงาน",
    partySize: "จำนวนผู้ร่วมงาน",
    partySizeOption: (size) => `${new Intl.NumberFormat("th").format(size)} คน`,
    partyLimit: (size) =>
      `คำเชิญนี้รองรับสูงสุด ${new Intl.NumberFormat("th").format(size)} คน`,
    note: "ข้อความถึงคู่บ่าวสาว (ไม่บังคับ)",
    notePlaceholder: "เขียนข้อความถึงคู่บ่าวสาว…",
    saving: "กำลังบันทึก…",
    submit: "ส่งคำตอบ",
    saved: "บันทึกคำตอบแล้ว",
    saveError: "ไม่สามารถบันทึกคำตอบได้ กรุณาลองอีกครั้ง",
    invalidInput: "กรุณาตรวจสอบคำตอบแล้วลองอีกครั้ง",
    privateLink:
      "ไม่ต้องสมัครบัญชีหรือใช้รหัสผ่าน โปรดเก็บลิงก์คำเชิญนี้ไว้เป็นส่วนตัว",
  },
  workspace: {
    label: "พื้นที่งานแต่ง",
    signOut: "ออกจากระบบ",
    eyebrow: "เรื่องราวของคุณ ในที่เดียว",
    title: "วางแผนวันสำคัญที่ทุกคนจะจดจำ",
    description: "เริ่มจากงานแต่งของคุณ เชิญแขก และติดตามทุกคำตอบในที่เดียว",
    opening: "กำลังเปิดพื้นที่ของคุณ…",
    weddings: "งานแต่งของคุณ",
    open: "กำลังเปิด",
    loading: "กำลังโหลด…",
    loadMoreWeddings: "โหลดงานแต่งเพิ่ม",
    beginTitle: "เริ่มจากวันสำคัญ",
    beginDescription:
      "สร้างงานแต่งเพื่อเริ่มรายชื่อแขกและคำเชิญส่วนตัว ยังไม่ต้องกำหนดวันก็ได้",
    createTitle: "สร้างงานแต่ง",
    createDescription: "พื้นที่สำหรับงานฉลองครั้งนี้",
    weddingName: "ชื่องานแต่ง",
    weddingDate: "วันแต่งงาน (ไม่บังคับ)",
    timeZone: "เขตเวลา",
    locale: "ภาษาของงานแต่ง",
    creating: "กำลังสร้าง…",
    create: "สร้างงานแต่ง",
    current: "งานที่กำลังวางแผน",
    datePending: "จะแจ้งวันภายหลัง",
    addGuestTitle: "เพิ่มแขก",
    addGuestDescription: "แขกแต่ละคนจะได้รับลิงก์คำเชิญส่วนตัว",
    guestName: "ชื่อแขก",
    emailOptional: "อีเมล (ไม่บังคับ)",
    guestAffiliation: "กลุ่มแขก",
    noAffiliation: "ไม่มีกลุ่ม",
    partyAllowance: "จำนวนคนที่เชิญ",
    adding: "กำลังเพิ่ม…",
    addGuest: "เพิ่มแขก",
    responses: "คำตอบรับ",
    guestList: "รายชื่อแขก",
    loaded: (count) =>
      `โหลดแล้ว ${new Intl.NumberFormat("th").format(count)} คน`,
    refreshing: "กำลังอัปเดต…",
    refreshResponses: "อัปเดตคำตอบรับ",
    noGuests: "ยังไม่มีแขก",
    noGuestsDescription: "เพิ่มแขกคนแรกเมื่อพร้อม",
    upTo: (count) =>
      `ร่วมงานได้สูงสุด ${new Intl.NumberFormat("th").format(count)} คน`,
    createInvitation: "สร้างคำเชิญ",
    invitationNotice:
      "ลิงก์ส่วนตัวนี้แสดงเฉพาะในครั้งนี้ โปรดคัดลอกไว้ก่อนออกจากหน้า",
    copyInvitation: "คัดลอกลิงก์คำเชิญ",
    copied: "คัดลอกแล้ว",
    loadMoreGuests: "โหลดแขกเพิ่ม",
    awaiting: "รอคำตอบ",
    attending: (count) =>
      `มาร่วมงาน · ${new Intl.NumberFormat("th").format(count)} คน`,
    declined: "ไม่มาร่วมงาน",
    affiliationEyebrow: "จัดระเบียบรายชื่อแขก",
    affiliationTitle: "กลุ่มแขก",
    affiliationDescription:
      "สร้างกลุ่มให้เหมาะกับงานนี้ได้เอง เมื่อลบกลุ่ม แขกในกลุ่มจะยังคงอยู่",
    newAffiliation: "ชื่อกลุ่มใหม่",
    color: "สี",
    addAffiliation: "เพิ่มกลุ่ม",
    noAffiliations: "ยังไม่มีกลุ่ม คุณเพิ่มแขกโดยไม่เลือกกลุ่มได้",
    save: "บันทึก",
    moveUp: (name) => `ย้าย ${name} ขึ้น`,
    moveDown: (name) => `ย้าย ${name} ลง`,
    delete: (name) => `ลบ ${name}`,
    affiliationName: (name) => `ชื่อกลุ่ม ${name}`,
    affiliationColor: (name) => `สีของ ${name}`,
    guestAffiliationLabel: (name) => `กลุ่มของ ${name}`,
    openInvitation: (name) => `เปิดคำเชิญของ ${name}`,
    deleteAffiliationConfirm: (name) =>
      `ลบกลุ่ม “${name}”? แขกในกลุ่มจะยังอยู่แต่ไม่มีกลุ่ม`,
    disconnected: "ยังไม่สามารถเชื่อมต่อพื้นที่วางแผนได้ กรุณาลองอีกครั้ง",
    createError: "ไม่สามารถสร้างงานแต่งได้",
    guestListError: "ไม่สามารถโหลดรายชื่อแขกได้",
    addGuestError: "ไม่สามารถเพิ่มแขกได้",
    addAffiliationError: "ไม่สามารถเพิ่มกลุ่มได้",
    updateAffiliationError: "ไม่สามารถแก้ไขกลุ่มได้",
    reorderAffiliationError: "ไม่สามารถจัดลำดับกลุ่มได้",
    deleteAffiliationError: "ไม่สามารถลบกลุ่มได้",
    setAffiliationError: "ไม่สามารถเปลี่ยนกลุ่มของแขกได้",
    invitationError: "ไม่สามารถสร้างคำเชิญได้",
    moreWeddingsError: "ไม่สามารถโหลดงานแต่งเพิ่มได้",
    moreGuestsError: "ไม่สามารถโหลดแขกเพิ่มได้",
    refreshError: "ไม่สามารถอัปเดตคำตอบรับได้",
    copyError: "คัดลอกไม่สำเร็จ โปรดเลือกและคัดลอกลิงก์คำเชิญด้วยตนเอง",
  },
  planning: {
    eyebrow: "การเตรียมงาน",
    title: "รายการเตรียมงาน",
    description: (name) => `เก็บรายการและกำหนดเวลาของ ${name} ไว้ด้วยกัน`,
    progress: "ความคืบหน้า",
    completedCount: (completed, total) =>
      `เสร็จแล้ว ${new Intl.NumberFormat("th").format(completed)} จาก ${new Intl.NumberFormat("th").format(total)}`,
    tasksCompleted: "งานที่เสร็จแล้ว",
    editTask: "แก้ไขงาน",
    addTaskTitle: "เพิ่มงาน",
    taskTitle: "ชื่องาน",
    category: "หมวดหมู่ (ไม่บังคับ)",
    dueDate: "กำหนดส่ง (ไม่บังคับ)",
    note: "บันทึกส่วนตัว (ไม่บังคับ)",
    saveTask: "บันทึกงาน",
    addTask: "เพิ่มงาน",
    cancelEdit: "ยกเลิกการแก้ไข",
    comingUp: "ใกล้ถึงกำหนด",
    overdue: "เลยกำหนด",
    allTasks: "งานทั้งหมด",
    showTasks: "แสดงงาน",
    all: "ทั้งหมด",
    toDo: "ต้องทำ",
    completed: "เสร็จแล้ว",
    loading: "กำลังโหลดงาน…",
    empty: "ยังไม่มีงาน",
    due: (date) => `กำหนด ${date}`,
    noDueDate: "ไม่มีกำหนดส่ง",
    complete: "ทำเสร็จ",
    reopen: "เปิดงานอีกครั้ง",
    edit: "แก้ไข",
    delete: "ลบ",
    actionLabel: (action, title) => `${action} ${title}`,
    deleteConfirm: (title) => `ลบ “${title}”? ไม่สามารถย้อนกลับได้`,
    loadMore: "โหลดงานเพิ่ม",
    loadError: "ไม่สามารถโหลดรายการเตรียมงานได้",
    saveError: "ไม่สามารถบันทึกงานได้",
    updateError: "ไม่สามารถอัปเดตงานได้",
    deleteError: "ไม่สามารถลบงานได้",
    moreError: "ไม่สามารถโหลดงานเพิ่มได้",
  },
  guest: {
    search: "ค้นหาแขก",
    searchPlaceholder: "ชื่อ อีเมล หรือเบอร์โทร",
    view: "มุมมองแขก",
    active: "ใช้งานอยู่",
    archived: "เก็บถาวร",
    affiliation: "กลุ่มแขก",
    allAffiliations: "ทุกกลุ่ม",
    unassigned: "ไม่มีกลุ่ม",
    rsvpStatus: "สถานะตอบรับ",
    allStatuses: "ทุกสถานะตอบรับ",
    pending: "รอคำตอบ",
    attending: "มาร่วมงาน",
    declined: "ไม่มาร่วมงาน",
    guestList: "รายชื่อแขก",
    listCount: (loaded, selected) =>
      `โหลดแล้ว ${new Intl.NumberFormat("th").format(loaded)} คน · เลือก ${new Intl.NumberFormat("th").format(selected)} คน`,
    selectVisible: "เลือกแขกที่แสดง",
    select: (name) => `เลือก ${name}`,
    bulkAffiliation: "เปลี่ยนกลุ่มพร้อมกัน",
    assignSelected: "กำหนดกลุ่มให้ที่เลือก",
    archiveSelected: "เก็บที่เลือกถาวร",
    noMatches: "ไม่พบแขกตามตัวกรองนี้",
    upTo: (count) =>
      `ร่วมงานได้สูงสุด ${new Intl.NumberFormat("th").format(count)} คน`,
    edit: "แก้ไข",
    archive: "เก็บถาวร",
    restore: "นำกลับ",
    action: (verb, name) => `${verb} ${name}`,
    createInvitation: "สร้างคำเชิญ",
    issueNewLink: "ออกลิงก์คำเชิญใหม่",
    issueNewLinkFor: (name) => `ออกลิงก์ใหม่ให้ ${name}`,
    replaceHint: "หากมีลิงก์เดิม การออกลิงก์ใหม่จะทำให้ลิงก์เดิมใช้ไม่ได้",
    openInvitation: (name) => `เปิดคำเชิญของ ${name}`,
    invitationNotice:
      "ลิงก์ส่วนตัวนี้แสดงเฉพาะในครั้งนี้ โปรดคัดลอกไว้ก่อนออกจากหน้า",
    copyInvitation: "คัดลอกลิงก์คำเชิญ",
    loading: "กำลังโหลด…",
    loadMore: "โหลดแขกเพิ่ม",
    awaiting: "รอคำตอบ",
    attendingCount: (count) =>
      `มาร่วมงาน · ${new Intl.NumberFormat("th").format(count)} คน`,
    guestName: "ชื่อแขก",
    emailOptional: "อีเมล (ไม่บังคับ)",
    email: "อีเมล",
    guestAffiliation: "กลุ่มแขก",
    noAffiliation: "ไม่มีกลุ่ม",
    partyAllowance: "จำนวนคนที่เชิญ",
    optionalDetails: "ข้อมูลติดต่อ ซอง และที่อยู่ (ไม่บังคับ)",
    phone: "เบอร์โทร",
    envelopeName: "ชื่อบนซอง",
    note: "บันทึก",
    includeAddress: "เพิ่มที่อยู่ไปรษณีย์",
    adding: "กำลังเพิ่ม…",
    addGuest: "เพิ่มแขก",
    addressLine1: "ที่อยู่บรรทัดที่ 1",
    addressLine2: "ที่อยู่บรรทัดที่ 2",
    locality: "เมือง/เขต",
    administrativeArea: "รัฐ/จังหวัด",
    postalCode: "รหัสไปรษณีย์",
    countryCode: "รหัสประเทศ",
    editGuest: (name) => `แก้ไข ${name}`,
    close: "ปิด",
    saving: "กำลังบันทึก…",
    saveGuest: "บันทึกแขก",
    archiveConfirm: (name) => `เก็บ ${name} ถาวร?`,
    bulkArchiveConfirm: (count) =>
      `เก็บแขก ${new Intl.NumberFormat("th").format(count)} คนถาวร? ลิงก์คำเชิญของพวกเขาจะถูกยกเลิก`,
    replaceConfirm: (name) =>
      `ออกลิงก์คำเชิญใหม่ให้ ${name}? ลิงก์เดิมจะใช้ไม่ได้ทันที โปรดแชร์ลิงก์ใหม่ให้แขก`,
    current: "งานที่กำลังวางแผน",
    addGuestTitle: "เพิ่มแขก",
    csvNotice:
      "แขกที่เก็บถาวรจะส่งออกได้เฉพาะในมุมมองเก็บถาวร และไฟล์จะไม่มีลิงก์คำเชิญ",
    exportCsv: "ส่งออก CSV ตามตัวกรอง",
    closeEnvelopes: "ปิดหน้าพิมพ์ซอง",
    printEnvelopes: "พิมพ์ซอง",
    refresh: "อัปเดตคำตอบรับ",
    loadError: "ไม่สามารถโหลดแขกได้",
    addError: "ไม่สามารถเพิ่มแขกได้",
    detailError: "ไม่สามารถโหลดข้อมูลแขกได้",
    saveError: "ไม่สามารถบันทึกข้อมูลแขกได้",
    archiveError: "ไม่สามารถเก็บแขกถาวรได้",
    restoreError: "ไม่สามารถนำแขกกลับได้",
    bulkAffiliationError: "ไม่สามารถเปลี่ยนกลุ่มพร้อมกันได้",
    bulkArchiveError: "ไม่สามารถเก็บแขกพร้อมกันได้",
    invitationError: "ไม่สามารถสร้างคำเชิญได้",
    replaceError: "ไม่สามารถออกลิงก์ใหม่ได้",
    copyError: "คัดลอกไม่สำเร็จ โปรดเลือกและคัดลอกลิงก์ด้วยตนเอง",
    exportError: "ไม่สามารถส่งออก CSV ได้",
  },
  metadata: {
    title: "LoveChapter — วางแผนงานแต่งและตอบรับคำเชิญ",
    description:
      "พื้นที่วางแผนงานแต่งสำหรับคู่รัก และหน้าตอบรับคำเชิญส่วนตัวสำหรับแขกโดยไม่ต้องสมัครบัญชี",
  },
  maintenance: {
    title: "LoveChapter ไม่สามารถใช้งานได้ชั่วคราว",
    message: "ไม่สามารถใช้งานได้ชั่วคราว กรุณาลองอีกครั้งในอีกสักครู่",
    notice:
      "เมื่อปรับปรุงเสร็จ แท็บที่เปิดค้างจะโหลดใหม่โดยอัตโนมัติ ข้อมูลในแบบฟอร์มที่ยังไม่บันทึกอาจสูญหาย",
    applyLanguage: "เปลี่ยนภาษา",
  },
};

export function getUiCopy(language: UiLanguage): UiCopy {
  return language === "th" ? th : en;
}
