// Source: countries-list@3.4.1 (MIT), package/countries.min.json.
// License text: docs/licenses/countries-list-MIT.txt.
// Non-ISO extensions AC, TA, and XK are excluded from the ISO country selector.
export const COUNTRY_NAMES: Readonly<Record<string, string>> = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Aland",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthelemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BQ: "Bonaire",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Democratic Republic of the Congo",
  CF: "Central African Republic",
  CG: "Republic of the Congo",
  CH: "Switzerland",
  CI: "Ivory Coast",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cabo Verde",
  CW: "Curacao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia and the South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "Saint Martin",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn Islands",
  PR: "Puerto Rico",
  PS: "Palestine",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "Sao Tome and Principe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Eswatini",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "East Timor",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Türkiye",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "U.S. Minor Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export const COUNTRY_CODES = Object.freeze(Object.keys(COUNTRY_NAMES));

export function isCountryCode(value: string): boolean {
  return Object.hasOwn(COUNTRY_NAMES, value);
}

// Country-language combinations from the same pinned source.
export const LOCALE_CANDIDATES = [
  "af-NA",
  "af-ZA",
  "am-ET",
  "ar-AE",
  "ar-BH",
  "ar-DJ",
  "ar-DZ",
  "ar-EG",
  "ar-ER",
  "ar-IL",
  "ar-IQ",
  "ar-JO",
  "ar-KM",
  "ar-KW",
  "ar-LB",
  "ar-LY",
  "ar-MA",
  "ar-MR",
  "ar-OM",
  "ar-PS",
  "ar-QA",
  "ar-SA",
  "ar-SD",
  "ar-SO",
  "ar-SY",
  "ar-TD",
  "ar-TN",
  "ar-YE",
  "ay-BO",
  "az-AZ",
  "be-BY",
  "bg-BG",
  "bi-VU",
  "bn-BD",
  "bs-BA",
  "bs-ME",
  "ca-AD",
  "ca-ES",
  "ch-GU",
  "ch-MP",
  "cs-CZ",
  "da-DK",
  "de-AT",
  "de-BE",
  "de-CH",
  "de-DE",
  "de-LI",
  "de-LU",
  "dv-MV",
  "dz-BT",
  "el-CY",
  "el-GR",
  "en-AG",
  "en-AI",
  "en-AS",
  "en-AU",
  "en-BB",
  "en-BM",
  "en-BS",
  "en-BW",
  "en-BZ",
  "en-CA",
  "en-CC",
  "en-CK",
  "en-CM",
  "en-CW",
  "en-CX",
  "en-DM",
  "en-ER",
  "en-FJ",
  "en-FK",
  "en-FM",
  "en-GB",
  "en-GD",
  "en-GG",
  "en-GH",
  "en-GI",
  "en-GM",
  "en-GS",
  "en-GU",
  "en-GY",
  "en-HK",
  "en-HM",
  "en-IE",
  "en-IM",
  "en-IN",
  "en-IO",
  "en-JE",
  "en-JM",
  "en-KE",
  "en-KI",
  "en-KN",
  "en-KY",
  "en-LC",
  "en-LR",
  "en-LS",
  "en-MF",
  "en-MH",
  "en-MP",
  "en-MS",
  "en-MT",
  "en-MU",
  "en-MW",
  "en-NA",
  "en-NF",
  "en-NG",
  "en-NR",
  "en-NU",
  "en-NZ",
  "en-PG",
  "en-PH",
  "en-PK",
  "en-PN",
  "en-PR",
  "en-PW",
  "en-RW",
  "en-SB",
  "en-SC",
  "en-SD",
  "en-SG",
  "en-SH",
  "en-SL",
  "en-SS",
  "en-SX",
  "en-SZ",
  "en-TC",
  "en-TK",
  "en-TO",
  "en-TT",
  "en-TV",
  "en-TZ",
  "en-UG",
  "en-UM",
  "en-US",
  "en-VC",
  "en-VG",
  "en-VI",
  "en-VU",
  "en-WS",
  "en-ZA",
  "en-ZM",
  "en-ZW",
  "es-AR",
  "es-BO",
  "es-BZ",
  "es-CL",
  "es-CO",
  "es-CR",
  "es-CU",
  "es-DO",
  "es-EC",
  "es-EH",
  "es-ES",
  "es-GQ",
  "es-GT",
  "es-GU",
  "es-HN",
  "es-MX",
  "es-NI",
  "es-PA",
  "es-PE",
  "es-PR",
  "es-PY",
  "es-SV",
  "es-UY",
  "es-VE",
  "et-EE",
  "eu-ES",
  "fa-AF",
  "fa-IR",
  "ff-BF",
  "ff-GN",
  "fi-FI",
  "fj-FJ",
  "fo-FO",
  "fr-BE",
  "fr-BF",
  "fr-BI",
  "fr-BJ",
  "fr-BL",
  "fr-CA",
  "fr-CD",
  "fr-CF",
  "fr-CG",
  "fr-CH",
  "fr-CI",
  "fr-CM",
  "fr-DJ",
  "fr-FR",
  "fr-GA",
  "fr-GF",
  "fr-GG",
  "fr-GN",
  "fr-GP",
  "fr-GQ",
  "fr-HT",
  "fr-JE",
  "fr-KM",
  "fr-LB",
  "fr-LU",
  "fr-MC",
  "fr-MF",
  "fr-MG",
  "fr-ML",
  "fr-MQ",
  "fr-NC",
  "fr-NE",
  "fr-PF",
  "fr-PM",
  "fr-RE",
  "fr-RW",
  "fr-SC",
  "fr-SN",
  "fr-TD",
  "fr-TF",
  "fr-TG",
  "fr-VU",
  "fr-WF",
  "fr-YT",
  "ga-IE",
  "gl-ES",
  "gn-AR",
  "gn-PY",
  "gv-IM",
  "he-IL",
  "hi-FJ",
  "hi-IN",
  "hr-BA",
  "hr-HR",
  "hr-ME",
  "ht-HT",
  "hu-HU",
  "hy-AM",
  "hy-CY",
  "id-ID",
  "is-IS",
  "it-CH",
  "it-IT",
  "it-SM",
  "it-VA",
  "ja-JP",
  "ka-GE",
  "kg-CD",
  "kk-KZ",
  "kl-GL",
  "km-KH",
  "ko-KP",
  "ko-KR",
  "ku-IQ",
  "ky-KG",
  "la-VA",
  "lb-LU",
  "ln-CD",
  "ln-CG",
  "lo-LA",
  "lt-LT",
  "lu-CD",
  "lv-LV",
  "mg-MG",
  "mh-MH",
  "mi-NZ",
  "mk-MK",
  "mn-MN",
  "ms-BN",
  "ms-MY",
  "ms-SG",
  "mt-MT",
  "my-MM",
  "na-NR",
  "nb-BV",
  "nb-NO",
  "nd-ZW",
  "ne-NP",
  "nl-AW",
  "nl-BE",
  "nl-BQ",
  "nl-CW",
  "nl-MF",
  "nl-NL",
  "nl-SR",
  "nl-SX",
  "nn-BV",
  "nn-NO",
  "no-BV",
  "no-NO",
  "no-SJ",
  "nr-ZA",
  "ny-MW",
  "oc-ES",
  "pa-AW",
  "pa-CW",
  "pl-PL",
  "ps-AF",
  "pt-AO",
  "pt-BR",
  "pt-CV",
  "pt-GW",
  "pt-MO",
  "pt-MZ",
  "pt-PT",
  "pt-ST",
  "pt-TL",
  "qu-BO",
  "rn-BI",
  "ro-MD",
  "ro-RO",
  "ru-AM",
  "ru-BY",
  "ru-KG",
  "ru-KZ",
  "ru-RU",
  "ru-TJ",
  "ru-TM",
  "ru-UZ",
  "rw-RW",
  "sg-CF",
  "si-LK",
  "sk-SK",
  "sl-SI",
  "sm-AS",
  "sm-WS",
  "sn-ZW",
  "so-SO",
  "sq-AL",
  "sq-ME",
  "sr-BA",
  "sr-ME",
  "sr-RS",
  "ss-SZ",
  "ss-ZA",
  "st-LS",
  "st-ZA",
  "sv-AX",
  "sv-FI",
  "sv-SE",
  "sw-CD",
  "sw-KE",
  "sw-TZ",
  "sw-UG",
  "ta-LK",
  "ta-SG",
  "tg-TJ",
  "th-TH",
  "ti-ER",
  "tk-AF",
  "tk-TM",
  "tl-PH",
  "tn-BW",
  "tn-ZA",
  "to-TO",
  "tr-CY",
  "tr-TR",
  "ts-ZA",
  "uk-UA",
  "ur-FJ",
  "ur-PK",
  "uz-AF",
  "uz-UZ",
  "ve-ZA",
  "vi-VN",
  "xh-ZA",
  "zh-CN",
  "zh-HK",
  "zh-MO",
  "zh-SG",
  "zh-TW",
  "zu-ZA",
] as const;
